<?php
require_once 'functions/utilities/get-cats.php';
require_once 'functions/utilities/order-by-rand.php';

require_once 'functions/acf.php';
require_once 'functions/array-sort.php';
require_once 'functions/archives.php';
require_once 'functions/autoversion.php';
require_once 'functions/blocks.php';
require_once 'functions/bootstrap-navwalker.php';
require_once 'functions/bootstrap-pagination.php';
require_once 'functions/comments.php';
require_once 'functions/custom-post-types.php';
require_once 'functions/emojis.php';
require_once 'functions/image-sizes.php';
require_once 'functions/natural-language-join.php';
require_once 'functions/orderby.php';
require_once 'functions/phone-format.php';
require_once 'functions/preconnect.php';
require_once 'functions/rdm-walker.php';
require_once 'functions/read-more.php';
require_once 'functions/relevanssi.php';
require_once 'functions/scripts.php';
require_once 'functions/setup.php';
require_once 'functions/styles.php';
require_once 'functions/trim-text.php';
require_once 'functions/users.php';
require_once 'functions/widgets-init.php';
require_once 'functions/yoast.php';